pages.rs: fix run of orphans packages
CachyOS/CachyOS-Welcome pull request #53
Opened 2023-03-06 00:03 UTC by Peppe289

This avoid "error: no targets specified (use -h for help)" when `pacman -Qtdq` is empty.

`pacman -Qtdq` can be started without root, and has a return value other than 0 if it finds no packages. So if it finds packages, it succeeds and goes to the true condition that it deletes packages. Otherwise do echo. (echo doesn't require root)

2023-03-06 14:25 UTC, NextWork123 requested changes
Hello, after a review of your code you can remove the "use std::process::Command;" and you can change all with: 
```// check if you have orphans packages.
let status = std::process::Command::new("pacman")
    .arg("-Qtdq")
    .status()
    .expect("Failed to execute pacman command");

if status.success() {
    let _ = utils::run_cmd_terminal(String::from("pacman -Rns $(pacman -Qtdq)"), true);
} else {
    let _ = utils::run_cmd_terminal(String::from("echo 'Not orphans packages'"), false);
}

2023-03-06 17:30 UTC, Peppe289 commented
> Hello, after a review of your code you can remove the "use std::process::Command;" and you can change all with:
> 
> ```
> let status = std::process::Command::new("pacman")
>     .arg("-Qtdq")
>     .status()
>     .expect("Failed to execute pacman command");
> 
> if status.success() {
>     let _ = utils::run_cmd_terminal(String::from("pacman -Rns $(pacman -Qtdq)"), true);
> } else {
>     let _ = utils::run_cmd_terminal(String::from("echo 'Not orphans packages'"), false);
> }
> ```

done bro

2023-03-06 17:35 UTC, NextWork123 commented
LGTM, i will wait for other reviews.

2023-03-06 18:29 UTC, vnepogodin requested changes

2023-03-06 18:29 UTC, vnepogodin commented on src/pages.rs
> +                let _ = utils::run_cmd_terminal(String::from("echo 'Not orphans packages'"), false);
I think that's rather unnecessary to launch terminal to display the message, so better would be here to spawn `gtk::MessageDialog` informing user that no orphans exist on the system.

Look into that line how it was made https://github.com/CachyOS/CachyOS-Welcome/blob/develop/src/pages.rs#L48

2023-03-06 18:29 UTC, vnepogodin commented on src/pages.rs
> +            let status = std::process::Command::new("pacman")
Use `Exec::cmd` instead of spawning bash shell to launch command( `std::process::Command::new("pacman")`)

so with path `/sbin/pacman`

2023-03-09 22:33 UTC, Peppe289 commented
@vnepogodin
I'm still learning Rust. I found this issue and tried to fix it. If possible, could you kindly make any additional changes by yourself?

2023-03-09 22:46 UTC, vnepogodin commented
> @vnepogodin I'm still learning Rust. I found this issue and tried to fix it. If possible, could you kindly make any additional changes by yourself?

Yeah sure I'll push commits with changes to your branch

2023-03-12 23:38 UTC, merged