feat: add outdated ISO version check
CachyOS/CachyOS-Welcome pull request #86
Opened 2024-11-06 18:41 UTC by SoulHarsh007

2024-11-06 20:02 UTC, SoulHarsh007 commented
translations pending

2024-11-06 20:03 UTC, vnepogodin commented
> translations pending

can be added later on

2024-11-06 20:50 UTC, SoulHarsh007 commented
translations need to be verified

2024-11-06 21:03 UTC, vnepogodin requested changes

2024-11-06 21:03 UTC, vnepogodin commented on i18n/ru/cachyos_hello.ftl
> +outdated-version-warning = Вы используете устаревшую версию ISO CachyOS, пожалуйста, рассмотрите возможность использования последней версии для установки
```diff
-outdated-version-warning = Вы используете устаревшую версию ISO CachyOS, пожалуйста, рассмотрите возможность использования последней версии для установки
+outdated-version-warning = Вы используете устаревшую версию CachyOS ISO, пожалуйста, рассмотрите возможность использования последней версии для установки
```

2024-11-06 21:13 UTC, ptr1337 requested changes

2024-11-06 21:13 UTC, ptr1337 commented on i18n/de/cachyos_hello.ftl
> +outdated-version-warning = Sie verwenden eine ältere Version des CachyOS ISO, bitte verwenden Sie die neueste Version für Installationen
outdated-version-warning = Sie verwenden eine ältere Version des CachyOS ISO, bitte verwenden Sie die neueste Version für Installationen

Du nutzt eine alte Version von CachyOS, bitte downloade die letzte Version runter

2024-11-06 21:13 UTC, ptr1337 commented on i18n/de/cachyos_hello.ftl
> +testing-iso-warning = Sie verwenden ein Test-ISO, Test-ISOs gelten nicht als stabil und einsatzbereit
Du verwendest eine alte Testing ISO, Testing-ISOs sind nicht stabil und getestet

2024-11-08 07:34 UTC, ptr1337 approved these changes

2024-11-08 18:34 UTC, vnepogodin approved these changes
Vielen Dank

2024-11-08 18:35 UTC, merged